### PR TITLE
Release Please

### PR DESCRIPTION
**Pull request by mariugul**
## Summary: Introduction of Release-Please
Adds [release-please](https://github.com/googleapis/release-please) to the project.

This pull request introduces Release-Please to automate release process. Release-Please is a tool that manages releases by generating changelogs, creating GitHub releases, and updating version numbers based on conventional commit messages. It works by analyzing merged PRs and determining the next version number (major, minor, or patch) according to the conventional commit spec. Once the changes are merged, Release-Please creates a release PR, which, when approved and merged, triggers the release workflow, ensuring a consistent and reliable release process without manual intervention.

**Note:** Only features and bugfixes are released. So if you commit a docs update or a refactor no PR or package is built and released.

## Release to PyPi
When release-please successfuly creates a release, poetry builds a new package of pikaraoke and publishes it.

## ToDo @vicwomg 
- [x] Create environment `pypi`. No need to put anything in there, just create it. `settings -> Environments -> create`.
- [x] Create a `secrets.RELEASE_PLEASE_TOKEN`.
- [ ] Merge and test this.

### CODE REVIEW

**Comment by mariugul** [comment]
@vicwomg please review this :smile: It will be really nice to have before merging any new PR's

**Comment by vicwomg** [comment]
I was looking yesterday, but got hung up on the secret. Do I need to create an account and generate a Release Please token myself to put into the env secrets? Where would I do that?

**Comment by mariugul** [comment]
> I was looking yesterday, but got hung up on the secret. Do I need to create an account and generate a Release Please token myself to put into the env secrets? Where would I do that? 

It should be just a GitHub secret to authorize release please to generate releases. I will find the steps.

**Comment by mariugul** [comment]
> I was looking yesterday, but got hung up on the secret. Do I need to create an account and generate a Release Please token myself to put into the env secrets? Where would I do that?

See [creating-a-fine-grained-personal-access-token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token) or [creating-a-personal-access-token-classic](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic). It should be pretty straight forward. Just name it `RELEASE_PLEASE_TOKEN` and give it sufficient permissions to read and write.

**Comment by vicwomg** [comment]
I created the token and merged, but there's a GHA error on master:

```
release-please failed: base (vicwomg/pikaraoke): Failed to parse manifest versions JSON: .release-please-manifest.json
Unexpected end of JSON input
```

lmk if there's more configuration needed on my part

**Comment by mariugul** [comment]
> I created the token and merged, but there's a GHA error on master:
> 
> ```
> release-please failed: base (vicwomg/pikaraoke): Failed to parse manifest versions JSON: .release-please-manifest.json
> Unexpected end of JSON input
> ```
> 
> lmk if there's more configuration needed on my part

I think you did it correctly. It looks like to me that it's a stupid thing that it isn't recognized as json. I will open a fix PR.

**Pull request merged**
