### PR TITLE
chore(master): release 1.5.0

### PR DESCRIPTION
**Pull request by vicwomg**
:robot: I have created a release *beep* *boop*
---

### Features

* add messages.mo file for es_VE translation ([3cd7d26](https://github.com/vicwomg/pikaraoke/commit/3cd7d2627f1e3ea2d44b482f896f9a6af750b1af))

### Bug Fixes

* song number overflows to add button when &gt; 999 songs [#379](https://github.com/vicwomg/pikaraoke/issues/379) ([a53c9e0](https://github.com/vicwomg/pikaraoke/commit/a53c9e00e144f5203bbecabe1a02f79dff739b68))

### Documentation

* move TROUBLESHOOTING to wiki ([331e814](https://github.com/vicwomg/pikaraoke/commit/331e814a5299189f5248c8595452af5985da3ef4))
* **readme:** recommend Bookworm OS over bullseye ([15598f2](https://github.com/vicwomg/pikaraoke/commit/15598f22e822e3c2014c63a866ecd3b72530698a))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by vicwomg** [comment]
@mariugul  Once again seems like I don't know what I'm doing with commit messages. Why did this bump to 1.5 ? 

These are the commits:

```
commit 488f308adf32ab72544755793b11476004fcf162 (HEAD -> documentation-and-various-fixes, origin/documentation-and-various-fixes)
Author: Vic Wong <vicwong@gmail.com>
Date:   Wed Sep 4 12:02:40 2024 -0700

    fix: song number overflows to add button when > 999 songs #379

commit 0e8118462c7826d90fe3512f34a7cdbfbee81bd0
Author: Vic Wong <vicwong@gmail.com>
Date:   Wed Sep 4 10:52:39 2024 -0700

    feat: add messages.mo file for es_VE translation

commit 3335aee47140e3fe9d448d81930d7c2880fb4359
Author: Vic Wong <vicwong@gmail.com>
Date:   Wed Sep 4 10:47:16 2024 -0700

    docs(readme): recommend Bookworm OS over bullseye

commit a7065fca5d6933ca7172ce5611e3d21bc11a5319
Author: Vic Wong <vicwong@gmail.com>
Date:   Wed Sep 4 10:39:31 2024 -0700

    docs: move TROUBLESHOOTING to wiki
```

**Comment by mariugul** [comment]
> @mariugul Once again seems like I don't know what I'm doing with commit messages. Why did this bump to 1.5 ? Is it the "feat:" tag?
> 
> These are the commits:
> 
> ```
> commit 488f308adf32ab72544755793b11476004fcf162 (HEAD -> documentation-and-various-fixes, origin/documentation-and-various-fixes)
> Author: Vic Wong <vicwong@gmail.com>
> Date:   Wed Sep 4 12:02:40 2024 -0700
> 
>     fix: song number overflows to add button when > 999 songs #379
> 
> commit 0e8118462c7826d90fe3512f34a7cdbfbee81bd0
> Author: Vic Wong <vicwong@gmail.com>
> Date:   Wed Sep 4 10:52:39 2024 -0700
> 
>     feat: add messages.mo file for es_VE translation
> 
> commit 3335aee47140e3fe9d448d81930d7c2880fb4359
> Author: Vic Wong <vicwong@gmail.com>
> Date:   Wed Sep 4 10:47:16 2024 -0700
> 
>     docs(readme): recommend Bookworm OS over bullseye
> 
> commit a7065fca5d6933ca7172ce5611e3d21bc11a5319
> Author: Vic Wong <vicwong@gmail.com>
> Date:   Wed Sep 4 10:39:31 2024 -0700
> 
>     docs: move TROUBLESHOOTING to wiki
> ```

Yes it's because you used `feat` which means a feature also known as minor increment. Release Please triggers on only 2 keywords (actually 3 but don't focus on the last one). That is `feat` and `fix`. 

1. If you do a bugfix, make a commit starting with `fix`. 
2. If you do a new feature implementation that adds features and doesn't break backwards compatibility, that's a `feat`.
3. If you do a major breaking change feature that's a `feat! <summary>` with a body saying `BREAKING-CHANGE:`. This is backwards breaking or API breaking changes.

That's basically it. So if you didn't actually make a feature it shouldn't be `feat` but something else. Perhaps `refactor`if you refactored or a `chore` if it's just some repo stuff or a `docs` if it's documentation.

The last keyword Release Please triggers on is `deps` but it's rarely used. You _can_ use it if you update the dependencies of the package for example.

**Comment by mariugul** [comment]
If you made a mistake you can just close this PR and revert your changes and re-commit.

**Comment by vicwomg** [comment]
Hmm, well given my options adding spanish language support sounds like more a `feat` than anything else. I suppose this is "correct"

**Comment by vicwomg** [comment]
:robot: Created releases:
- [1.5.0](https://github.com/vicwomg/pikaraoke/releases/tag/1.5.0)
:sunflower:

**Comment by mariugul** [comment]
> Hmm, well given my options adding spanish language support sounds like more a `feat` than anything else. I suppose this is "correct"

Then great :smile:

**Pull request merged**
