### PR TITLE
#277 Move video rendering fully to ffmpeg and html

### PR DESCRIPTION
**Pull request by vicwomg**

### CODE REVIEW

**Comment by Deastrom** [comment]
Gave it a shot, no luck.

```logs
[2023-12-03 19:27:32] INFO: Song starting: Blink-182 • All The Small Things (CC) 🎤 [Karaoke] [Instrumental Lyrics]
[2023-12-03 19:27:32] DEBUG: Stream is playing
[2023-12-03 19:27:33] INFO: Song ending: Blink-182 • All The Small Things (CC) 🎤 [Karaoke] [Instrumental Lyrics]
[2023-12-03 19:27:33] DEBUG: Killing ffmpeg process
```

logs don't say much. i'm pretty happy to run it from a browser in wsl2 (since it supports gui on windows now).  I'm having other ffmpeg errors too. I imagine it's the python and ffmpeg version i'm running

python 3.12.0
ffmpeg version n6.1

here's my pip freeze ouput. if you have a specific version of python you're deving on, let me know. I just wanted to let you know this is great work

```
annotated-types==0.6.0
attrs==23.1.0
autocommand==2.2.2
Babel==2.9.1
Brotli==1.1.0
certifi==2023.11.17
charset-normalizer==3.3.2
cheroot==10.0.0
CherryPy==18.8.0
click==8.1.7
ffmpeg-python==0.2.0
Flask==2.2.5
Flask-Babel==2.0.0
flask-paginate==2021.10.29
future==0.18.3
h11==0.14.0
idna==3.6
inflect==7.0.0
itsdangerous==2.1.2
jaraco.collections==4.3.0
jaraco.context==4.3.0
jaraco.functools==4.0.0
jaraco.text==3.12.0
Jinja2==3.0.3
MarkupSafe==2.1.3
more-itertools==10.1.0
mutagen==1.47.0
outcome==1.3.0.post0
portend==3.2.0
psutil==5.9.6
pycryptodomex==3.19.0
pydantic==2.5.2
pydantic_core==2.14.5
pypng==0.20220715.0
PySocks==1.7.1
pytz==2023.3.post1
qrcode==7.4.2
requests==2.31.0
selenium==4.15.2
setuptools==69.0.2
sniffio==1.3.0
sortedcontainers==2.4.0
tempora==5.5.0
trio==0.23.1
trio-websocket==0.11.1
typing_extensions==4.8.0
Unidecode==1.3.7
urllib3==2.1.0
websockets==12.0
Werkzeug==3.0.1
wsproto==1.2.0
yt-dlp==2023.11.16
zc.lockfile==3.0.post1
```

I can create an issue if you like, but since this specific to this branch, i think the PR is an appropriate place

**Comment by vicwomg** [comment]
I’m still a bit lost. Can you explain further what your setup is? I’m not
familiar with wsl2. In my testing, I have run a PiKaraoke server in
windows, raspberry pi, and osx and accessed it remotely with another
machine.

Example: raspberry pi host
./pikaraoke.sh —hide-splash

Launches the server on http://pikaraoke.local:5555 and does not open the
splash screen on the host server.

OSX splash screen client: open http://pikaraoke.local:5555/splash

iPhone user client. Open the QR code url shown on the splash screen. Queue
up songs, they play on the osx client.

**Comment by Deastrom** [comment]
wsl2 is windows subsystem for linux. it's basically a baked in vm for linux things so i don't have to do weird conda things on windows 😛 
i'll keep trying previous versions of python see if that helps at all

**Comment by vicwomg** [comment]
Ah I see, well you're covering new territory here. I got this working on
Windows natively with python3 and virtual env, no other package managers
(like conda( necessary so you may want to try that. I haven't updated the
readme yet, but the installation should be: install the latest ffmpeg and
chrome, then run ./setup.bat (sets up venv and pulls requirements down to
the virtual env) then launch with ./pikaraoke.bat.

Now that I'm thinking this through, I do actually recall on the first
stream Windows popped up a security warning about allowing ffmpeg to stream
over port 5556, I hit the button to accept this server side and it didn't
bother me again. Maybe wsl2 is having issues with that piece.

**Pull request merged**
