### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by mawkee**
Complete translation for Brazilian Portuguese

### CODE REVIEW

**Comment by lvmasterrj** [comment]
Nice one!

**Comment by redmeneses** [comment]
How do i use this translation? Explain to a n00b please!

**Comment by mawkee** [comment]
> How do i use this translation? Explain to a n00b please!

IIRC you just have to use it normally; if the device is set up to pt-br, it should show in BR automatically

**Comment by vicwomg** [comment]
I'll get this merged into main. Then at that point it should just be a matter of running `git pull` to fetch the latest version, then relaunching pikaraoke. Sorry for the delay.

**Comment by vicwomg** [comment]
Ok @redmeneses this is now in the main branch. You should be able to log on to your pi, `cd ~/pikaraoke` then run `git pull` for the updated version with translation. It should automatically detect your region and apply translation on next launch.

**Pull request merged**
