### PR TITLE
chore(master): release 0.1.0

### PR DESCRIPTION
**Pull request by vicwomg**
:robot: I have created a release *beep* *boop*
---

### Features

* add a setup script ([2d0e973](https://github.com/vicwomg/pikaraoke/commit/2d0e973717892ec072afb0344a969f471e0400e9))
* create python package ([0c97670](https://github.com/vicwomg/pikaraoke/commit/0c97670bea36eb0f8affa17fd23212f64bbed6a7))
* upgrade yt-dlp on all pikaraoke runs ([fedd6ed](https://github.com/vicwomg/pikaraoke/commit/fedd6ed64e53a1e0fec4bc75368e767b57fa6b7e))

### Bug Fixes

* 287 bug: paths with spaces don't work ([f25e326](https://github.com/vicwomg/pikaraoke/commit/f25e32676066754c69f7bfb5b75b54c84ec7d866))
* modify files minimally to make it run ([168abbb](https://github.com/vicwomg/pikaraoke/commit/168abbb069412c1c2913a222623b0bfa0e5ccdf7))
* python-pygame name for apt installation ([be028ab](https://github.com/vicwomg/pikaraoke/commit/be028ab030f3a5a9e6463d9bcbabf6f957ea0dfe))
* resolve issues with commitlint attempt [#1](https://github.com/vicwomg/pikaraoke/issues/1) ([4c375e6](https://github.com/vicwomg/pikaraoke/commit/4c375e665f2333d527335e16d7db6093d96ed5a5))

### Documentation

* add conventional commits badge ([0c63c7d](https://github.com/vicwomg/pikaraoke/commit/0c63c7db4933bfe4549b19b04dc7a46a342039a6))
* rewrite README ([78df2e8](https://github.com/vicwomg/pikaraoke/commit/78df2e8bfc492c75d3befc09b777fdef8d4855fb))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by mariugul** [comment]
This is the first release PR from release please. This is how it looks like. Right now it's a bit confused because it's the first one. We should pin it to the correct version and it will be correct from there on and out. These PR's can be closed if they are incorrect.

**Comment by mariugul** [comment]
If you merge PR's like these, it will update the files like in the files changed tab and create a GitHub release. That will trigger pushing a package to PyPi.

**Comment by mariugul** [comment]
@vicwomg I would close this PR before mergin my other PR. Release please can only open one at a time. If you would like to give me some more priviliges in this repo it would be easier for me to fix these things quickly.

**Comment by vicwomg** [comment]
I’ll enable access when I get back to the computer. Probably best that you
drive this piece of the process

**Pull request closed without merging**
