### PR TITLE
hd video

### PR DESCRIPTION
**Pull request by tommhendrick**
This allows hd video and audio that can play on omxplayer by omitting webm format

### CODE REVIEW

**Comment by tommhendrick** [comment]
I believe it combines them into one file after but not sure if it uses ffmpeg. I didn't have to install anything extra on the PI for it to work.

**Comment by vicwomg** [comment]
When I tried this, I got two separate files. Is there a missing parameter, like --merge-output-format mp4  ?

**Comment by tommhendrick** [comment]
just checked. it uses FFMPEG to combine them. however on my rpi3 b+ I never manually installed it so maybe it came with something. So I guess the solution to hd video and audio is to include ffmpeg in the install script if you truly want HD. and then use my line above.

-best will only find the best single file which usually isn't HD.

**Comment by vicwomg** [comment]
manually merged this in. setup.sh now includes ffmpeg and passing --high-quality to app.py will utilize the following quality specification to the -f option in youtube-dl: 

```bestvideo[ext!=webm][height<=1080]+bestaudio[ext!=webm]/best[ext!=webm]```

**Pull request closed without merging**
